apiVersion: v1
kind: Pod
metadata:
  name: example-nodeport
  labels:
    app: httpd
  namespace: demo2022
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: example-nodeport
      image: 'quay.io/redhattraining/hello-world-nginx:v1.0'
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: example-nodeport
  labels:
    name: eample-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    name: example-nodeport
