---
apiVersion: v1
kind: Service
metadata:
  name: optus-example-nodeport
  labels:
    name: optus-example
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    name: optus-example
